### ISSUE TITLE
NSA not working on Inbound shipment

### ISSUE THREAD

**Issue by RezaSeedin** [burkybang/NetSuite-Advanced-Feedback#11]
**Describe the bug**
Inbound shipment does not use 1.0 code thus NSA does not seem to work

**To Reproduce**
1. Transaction / Purchase/ inbound shipment
2. NSA is not active

**Comment by burkybang** [comment]
Most of NSA will not work, but a lot of it does. The Inbound Shipment and Invoice Group record types are on what I like to call the "new UI". There are other various pages also using the new UI. The HTML on these new UI pages is 100% a different structure. When NetSuite first introduced these new pages, literally nothing worked, but over time, I started rewriting some of the features specifically for these pages while also maintaining the same features for regular pages. I don't plan on rewriting every single feature just for these pages because:

- There aren't very many new UI pages.
- Many of the features are just too difficult or near impossible to rewrite for the new UI.
